import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[window]
padding = { x = 15, y = 15 }
decorations = "full"
title = "aaarslan"
dynamic_title = true

[scrolling]
history = 20000

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 14.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
