# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.autojump]
github = "wting/autojump"
dir = "bin"
apply = [
    "PATH",
    "source",
]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins."z.lua"]
github = "skywind3000/z.lua"

[plugins.docker-zsh-completion]
github = "greymd/docker-zsh-completion"

[plugins.rust-zsh-completions]
github = "ryutok/rust-zsh-completions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["git-prompt.plugin.zsh"]


# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
